export const tem1 = {
  id: 1,
  template_name: "templateName1",
  type: 1,
  createdBy: "sasina.mod",
  updateBy: "sasina.mod",
  lastUpdate: "2022-02-08 18:52:25",
  status: 1,
  components: [
    {
      id: "247",
      key: "OKRs_label_10_1",
      size: "long",
      type: "title",
      align: "left",
      index: 30,
      label: "10.1 รายรับที่ใช้ในโครงการ ",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "246",
      key: "OKRs_label_10",
      size: "long",
      type: "title",
      align: "left",
      index: 29,
      label: "10.  งบประมาณ",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "245",
      key: "OKRs_label_3",
      size: "long",
      type: "title",
      align: "left",
      index: 12,
      label: "3.  ผลลัพธ์หลัก",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "244",
      key: "measure_quality",
      size: "long",
      type: "select",
      align: "left",
      index: 11,
      label: "2.5 ตัวชี้วัดด้านการประเมินการประกันคุณภาพ (ถ้ามี)",
      options: [
        {
          index: 1,
          label: "ตัวชี้วัด 1",
          value: "1",
        },
        {
          index: 2,
          label: "ตัวชี้วัด 2",
          value: "2",
        },
      ],
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "243",
      key: "measure_skill",
      size: "long",
      type: "select",
      align: "left",
      index: 10,
      label: "2.4 ตัวชี้วัดด้านทักษะการเรียนรู้ในศตวรรษที่ 21 (ถ้ามี) ",
      options: [
        {
          index: 1,
          label: "ตัวชี้วัด 1",
          value: "1",
        },
        {
          index: 2,
          label: "ตัวชี้วัด 2",
          value: "2",
        },
      ],
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "242",
      key: "measure_student",
      size: "long",
      type: "select",
      align: "left",
      index: 9,
      label:
        "2.3 ตัวชี้วัดด้านกิจกรรมการเรียนรู้แบบบูรณาการของนักศึกษา (ถ้ามี)",
      options: [
        {
          index: 1,
          label: "ตัวชี้วัด 1",
          value: "1",
        },
        {
          index: 2,
          label: "ตัวชี้วัด 2",
          value: "2",
        },
      ],
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "241",
      key: "measure_sdgs",
      size: "long",
      type: "select",
      align: "left",
      index: 8,
      label: "2.2 ตัวชี้วัดด้านความสอดคล้องกับ SDGs (ถ้ามี)",
      options: [
        {
          index: 1,
          label: "ตัวชี้วัด 1",
          value: "1",
        },
        {
          index: 2,
          label: "ตัวชี้วัด 2",
          value: "2",
        },
      ],
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "240",
      key: "measure_f",
      size: "long",
      type: "select",
      align: "left",
      index: 7,
      label: "2.1 ตัวชี้วัดด้านแผน",
      options: [
        {
          index: 1,
          label: "ตัวชี้วัด 1",
          value: "1",
        },
        {
          index: 2,
          label: "ตัวชี้วัด 2",
          value: "2",
        },
      ],
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "239",
      key: "OKRs_label_2",
      size: "long",
      type: "title",
      align: "left",
      index: 6,
      label:
        "2.  สอดคล้องกับแผนยุทธศาสตร์ของคณะ ฯ  (สอดคล้องกับตัวชี้วัดของคณะข้อใด)",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "130",
      key: "OKRs_FinanceNumber",
      size: "short",
      type: "input",
      align: "left",
      index: 61,
      label: "เลขคุมยอด",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "129",
      key: "OKRs_Date",
      size: "short",
      type: "day",
      align: "left",
      index: 60,
      label: "วันที่รับ",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "128",
      key: "OKRs_Title",
      size: "long",
      type: "input",
      align: "left",
      index: 3,
      label: "ชื่อเรื่อง",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "127",
      key: "OKRs_BookNumber",
      size: "short",
      type: "input",
      align: "left",
      index: 2,
      label: "เลขที่หนังสือ",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "126",
      key: "OKRs_Ids",
      size: "short",
      type: "input",
      align: "left",
      index: 59,
      label: "เลขรับ",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "125",
      key: "OKRs_Officer",
      size: "long",
      type: "input",
      align: "left",
      index: 62,
      label: "เจ้าของเรื่อง",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "124",
      key: "OKRs_evaluation",
      size: "long",
      type: "textArea",
      align: "left",
      index: 48,
      label: "12. การประเมินผล",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "123",
      key: "OKRs_expectedbenefits",
      size: "long",
      type: "textArea",
      align: "left",
      index: 47,
      label: "11. ประโยชน์ที่คาดว่าจะได้รับ",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "122",
      key: "OKRs_LocationInfo",
      size: "short",
      type: "input",
      align: "left",
      index: 28,
      label: "สถานที่จัดกิจกรรม",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "121",
      key: "OKRs_Location",
      size: "short",
      type: "radio",
      align: "left",
      index: 27,
      label: "รูปแบบการจัดกิจกรรม",
      options: [
        {
          index: 1,
          label: "Online",
          value: "Online",
        },
        {
          index: 2,
          label: "Onsite",
          value: "Onsite",
        },
      ],
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "120",
      key: "OKRs_Period",
      size: "long",
      type: "input",
      align: "left",
      index: 26,
      label: "9. ระยะเวลาดำเนินการ",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "119",
      key: "OKRs_PDCAMonth",
      index: 25,
      label: "ระยะเวลาดำเนินการ",
      required: true,
    },
    {
      id: "118",
      key: "OKRs_PDCA",
      index: 24,
      label: "8. วิธีการดำเนินการ",
      required: true,
    },
    {
      id: "117",
      key: "OKRs_TargetGroupNum",
      index: 23,
      label: "จำนวนกลุ่มเป้าหมาย",
      required: true,
    },
    {
      id: "116",
      key: "OKRs_TargetGroup",
      index: 22,
      label: "7. กลุ่มเป้าหมาย",
      required: true,
    },
    {
      id: "115",
      key: "OKRs_Object",
      size: "long",
      type: "textArea",
      align: "left",
      index: 21,
      label: "6. วัตถุประสงค์",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "114",
      key: "OKRs_Principle",
      size: "long",
      type: "textArea",
      align: "left",
      index: 20,
      label: "5. หลักการและเหตุผล",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "113",
      key: "OKRs_QA",
      size: "short",
      type: "input",
      align: "left",
      index: 58,
      label: "ประกันคุณภาพ",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "112",
      key: "OKRs_21CenturySkillPercent",
      size: "short",
      type: "input",
      align: "left",
      index: 57,
      label: "ร้อยละของทักษะนักศึกษา",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "111",
      key: "OKRs_21CenturySkill",
      size: "short",
      type: "select",
      align: "left",
      index: 56,
      label: "ทักษะนักศึกษา",
      options: [
        {
          index: 1,
          label: "1",
          value: "1",
        },
        {
          index: 2,
          label: "2",
          value: "2",
        },
        {
          index: 3,
          label: "3",
          value: "3",
        },
      ],
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "110",
      key: "OKRs_Student_Unit",
      size: "long",
      type: "input",
      align: "left",
      index: 55,
      label: "หน่วยกิจกรรมนักศึกษา",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "109",
      key: "OKRs_SDGs",
      size: "long",
      type: "select",
      align: "left",
      index: 54,
      label: "SDGs",
      options: [
        {
          index: 1,
          label: "1",
          value: "1",
        },
        {
          index: 2,
          label: "2",
          value: "2",
        },
        {
          index: 3,
          label: "3",
          value: "3",
        },
      ],
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "108",
      key: "OKRs_Pillar",
      size: "long",
      type: "select",
      align: "left",
      index: 53,
      label: "เสาหลัก",
      options: [
        {
          index: 1,
          label: "A",
          value: "A",
        },
        {
          index: 2,
          label: "B",
          value: "B",
        },
        {
          index: 3,
          label: "C",
          value: "c",
        },
      ],
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "107",
      key: "OKRs_Tactics",
      size: "long",
      type: "textArea",
      align: "left",
      index: 52,
      label: "กลยุทธ์",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "106",
      key: "OKRs_Strategy",
      size: "long",
      type: "select",
      align: "left",
      index: 51,
      label: "ประเด็นยุทธศาสตร์",
      options: [
        {
          index: 1,
          label: "ประเด็นยุทศาสตร์ 1",
          value: "1",
        },
        {
          index: 2,
          label: "ประเด็นยุทศาสตร์ 2",
          value: "2",
        },
        {
          index: 3,
          label: "ประเด็นยุทศาสตร์ 3",
          value: "3",
        },
        {
          index: 4,
          label: "ประเด็นยุทศาสตร์ 4",
          value: "4",
        },
        {
          index: 5,
          label: "ประเด็นยุทศาสตร์ 5",
          value: "5",
        },
        {
          index: 6,
          label: "ประเด็นยุทศาสตร์ 6",
          value: "6",
        },
        {
          index: 7,
          label: "ประเด็นยุทศาสตร์ 7",
          value: "7",
        },
        {
          index: 8,
          label: "ประเด็นยุทศาสตร์ 8",
          value: "8",
        },
      ],
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "105",
      key: "OKRs_Result_Desc",
      size: "long",
      type: "textArea",
      align: "left",
      index: 19,
      label: "4. รายละเอียดผลการดำเนินงานตามค่าเป้าหมาย",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "104",
      key: "OKRs_Success",
      size: "short",
      type: "radio",
      align: "left",
      index: 50,
      label: "ความสำเร็จ",
      options: [
        {
          index: 1,
          label: "สำเร็จ",
          value: "success",
        },
        {
          index: 2,
          label: "ไม่สำเร็จ",
          value: "failed",
        },
      ],
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "103",
      key: "OKRs_Result",
      size: "short",
      type: "input",
      align: "left",
      index: 17,
      label: "3.4 ผลงานตามค่าเป้าหมาย",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "102",
      key: "OKRs_Result_Value ",
      size: "short",
      type: "input",
      align: "left",
      index: 18,
      label: "หน่วยวัดค่าเป้าหมาย",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "101",
      key: "OKRs_Unit_Value",
      size: "short",
      type: "input",
      align: "left",
      index: 16,
      label: "หน่วยวัดค่าเป้าหมาย",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "100",
      key: "OKRs_Value",
      size: "short",
      type: "input",
      align: "left",
      index: 15,
      label: "3.3 ค่าเป้าหมายของตัวชี้วัด",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "99",
      key: "OKRs_measure_unit",
      size: "long",
      type: "input",
      align: "left",
      index: 14,
      label: "3.2 หน่วยวัดของตัวชี้วัด",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "98",
      key: "OKRs_measure_title",
      size: "long",
      type: "input",
      align: "left",
      index: 13,
      label: "3.1 ชื่อตัวชี้วัด",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "97",
      key: "OKRs_Type",
      size: "long",
      type: "input",
      align: "left",
      index: 4,
      label: "ประเภท",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "96",
      key: "OKRs_PIC",
      size: "long",
      type: "input",
      align: "left",
      index: 49,
      label: "13. ผู้รับผิดชอบโครงการ",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "95",
      key: "OKRs_Budget3",
      size: "short",
      type: "input",
      align: "left",
      index: 34,
      label: "งบประมาณคงเหลือ",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "94",
      key: "OKRs_Budget2",
      size: "short",
      type: "input",
      align: "left",
      index: 33,
      label: "งบประมาณที่ใช้",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "93",
      key: "OKRs_Budgetlist2",
      rows: 5,
      size: "long",
      type: "table",
      align: "left",
      index: 46,
      label: "10.2 รายการค่าใช้จ่าย",
      columns: [
        {
          index: 1,
          colKey: "no",
          colLabel: "ลำดับที่",
        },
        {
          index: 2,
          colKey: "list_name",
          colLabel: "รายการ",
        },
        {
          index: 3,
          colKey: "budget",
          colLabel: "งบประมาณ",
        },
      ],
      required: true,
      isSubTitle: true,
    },
    {
      id: "92",
      key: "OKRs_BudgetCode4",
      size: "short",
      type: "input",
      align: "left",
      index: 45,
      label: "รหัสโครงการที่ใช้",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "91",
      key: "OKRs_BudgetCode3",
      size: "short",
      type: "input",
      align: "left",
      index: 44,
      label: "รหัสที่ใช้",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "90",
      key: "OKRs_Budget1",
      size: "short",
      type: "input",
      align: "left",
      index: 32,
      label: "งบประมาณที่จัดสรร",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "89",
      key: "OKRs_Projectlist1",
      rows: 5,
      size: "long",
      type: "table",
      align: "left",
      index: 43,
      label: "รายการโครงการ/กิจกรรมที่จัดสรร",
      columns: [
        {
          index: 1,
          colKey: "no",
          colLabel: "ลำดับที่",
        },
        {
          index: 2,
          colKey: "list_name",
          colLabel: "รายการ",
        },
        {
          index: 3,
          colKey: "budget",
          colLabel: "งบประมาณ",
        },
      ],
      required: true,
    },
    {
      id: "88",
      key: "OKRs_BudgetCode2",
      size: "short",
      type: "input",
      align: "left",
      index: 42,
      label: "รหัสโครงการที่จัดสรร",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "87",
      key: "OKRs_BudgetCode1",
      size: "short",
      type: "input",
      align: "left",
      index: 41,
      label: "รหัสที่จัดสรร",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "86",
      key: "OKRs_Budgetpay",
      size: "short",
      type: "input",
      align: "left",
      index: 35,
      label: "งบรายจ่าย",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "85",
      key: "OKRs_BudgetActivity",
      size: "long",
      type: "input",
      align: "left",
      index: 40,
      label: "กิจกรรม",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "84",
      key: "OKRs_BudgeFund",
      size: "long",
      type: "input",
      align: "left",
      index: 39,
      label: "กองทุน",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "83",
      key: "OKRs_BudgetJob",
      size: "long",
      type: "input",
      align: "left",
      index: 38,
      label: "งาน",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "82",
      key: "OKRs_BudgetPlan",
      size: "long",
      type: "input",
      align: "left",
      index: 37,
      label: "แผนงาน",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "81",
      key: "OKRs_BudgetPersonal",
      size: "long",
      type: "input",
      align: "left",
      index: 36,
      label: "ผู้รับผิดชอบงบประมาณ",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "80",
      key: "OKRs_BudgetType",
      size: "long",
      type: "input",
      align: "left",
      index: 31,
      label: "ประเภทงบประมาณ",
      required: true,
      isSubTitle: true,
      labelPosition: "vertical",
    },
    {
      id: "79",
      key: "OKRs_Years",
      size: "short",
      type: "input",
      align: "left",
      index: 1,
      label: "ปี",
      required: true,
      labelPosition: "vertical",
    },
    {
      id: "1",
      key: "OKRs_Project",
      size: "long",
      type: "input",
      align: "left",
      index: 5,
      label: "1.ชื่อโครงการ",
      required: true,
      labelPosition: "vertical",
    },
  ],
};

export const tem2 = {
  id:2,
  template_name: 'templateName2',
  type: 2,
  createdBy: 'sasina.mod',
  updateBy: 'sasina.mod',
  lastUpdate: '2022-02-08 18:52:25',
  status: 1,
  components: [
    {
      index: 1,
      labelPosition: 'horizontal',
      type: 'input',
      key: 'input_1',
      label: 'เลขหนังสือ อว',
      size: 'long',
      align: "left"
    },
    {
      index: 2,
      labelPosition: 'horizontal',
      type: 'input',
      key: 'input_2',
      label: 'ชื่อเรื่อง',
      size: 'long',
      align: "left"
    },
    {
      index: 3,
      labelPosition: 'horizontal',
      type: 'input',
      key: 'input_3',
      label: '1.ชื่อโครงการ',
      size: 'long',
      align: "left"
    }
    ,
    {
      index: 4,
      labelPosition: 'horizontal',
      type: 'title',
      key: 'input_4',
      label: '2.สอดคล้องกับแผนยุทธศาสตร์ของคณะ ฯ  (สอดคล้องกับตัวชี้วัดของคณะข้อใด)',
      size: 'long',
      align: "left"
    },
    {
      index: 5,
      labelPosition: 'vertical',
      type: 'input',
      key: 'input_5',
      label: '2.1 ตัวชี้วัดด้านแผน',
      size: 'long',
      align: "left"
    },
    {
      index: 6,
      labelPosition: 'vertical',
      type: 'input',
      key: 'input_6',
      label: '2.2ตัวชี้วัดด้านความสอดคล้องกับ SDGs (ถ้ามี) ',
      size: 'long',
      align: "left"
    },
    {
      index: 7,
      labelPosition: 'vertical',
      type: 'input',
      key: 'input_7',
      label: '2.3 ตัวชี้วัดด้านกิจกรรมการเรียนรู้แบบบูรณาการของนักศึกษา (ถ้ามี) ',
      size: 'long',
      align: "left"
    },
    {
      index: 8,
      labelPosition: 'vertical',
      type: 'input',
      key: 'input_8',
      label: '2.4 ตัวชี้วัดด้านทักษะการเรียนรู้ในศตวรรษที่ 21 (ถ้ามี) ',
      size: 'short',
      align: "left"
    },
    {
      index: 9,
      labelPosition: 'horizontal',
      type: 'input',
      key: 'input_9',
      label: 'คิดเป็นร้อยละ ',
      size: 'short',
      align: "left"
    },
    {
      index: 10,
      labelPosition: 'vertical',
      type: 'input',
      key: 'input_10',
      label: '2.5 ตัวชี้วัดด้านการประเมินการประกันคุณภาพ (ถ้ามี) ',
      size: 'long',
      align: "left"
    },
    {
      index: 11,
      labelPosition: 'horizontal',
      type: 'textArea',
      key: 'input_11',
      label: '3.ผลลัพธ์หลัก',
      size: 'long',
      align: "left"
    },{
      index: 12,
      labelPosition: 'horizontal',
      type: 'textArea',
      key: 'input_12',
      label: '4.  รายละเอียดผลการดำเนินงานตามค่าเป้าหมาย ',
      size: 'long',
      align: "left"
    },
  ]
};

